//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SkaldKurs
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (Накладная CustomAttributes)

    // *** End programmer edit section *** (Накладная CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НакладнаяE", new string[] {
            "Примечание as \'Примечание\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Вес as \'Вес\'",
            "Статус as \'Статус\'",
            "ФИОПолучателя as \'Ф и о получателя\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Номер as \'Номер\'",
            "Заказ as \'Заказ\'",
            "Заказ.ДатаОплаты as \'Дата оплаты\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Заказ.ДатаОплаты",
            "Сотрудник.Фамилия"})]
    [AssociatedDetailViewAttribute("НакладнаяE", "ЗаписьВНакладной", "ЗаписьВНакладнойE", true, "", "Запись в накладной", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("НакладнаяE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаОплаты")]
    [MasterViewDefineAttribute("НакладнаяE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("НакладнаяL", new string[] {
            "Примечание as \'Примечание\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Вес as \'Вес\'",
            "Статус as \'Статус\'",
            "ФИОПолучателя as \'Ф и о получателя\'",
            "ДатаЗаполнения as \'Дата заполнения\'",
            "Номер as \'Номер\'",
            "Заказ.ДатаОплаты as \'Дата оплаты\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Накладная : IIS.SkaldKurs.Документ
    {
        
        private string fПримечание;
        
        private System.DateTime fДатаОтгрузки;
        
        private double fВес;
        
        private IIS.SkaldKurs.СостояниеНакладной fСтатус;
        
        private string fФИОПолучателя;
        
        private IIS.SkaldKurs.Заказ fЗаказ;
        
        private IIS.SkaldKurs.Сотрудник fСотрудник;
        
        private IIS.SkaldKurs.DetailArrayOfЗаписьВНакладной fЗаписьВНакладной;
        
        // *** Start programmer edit section *** (Накладная CustomMembers)

        // *** End programmer edit section *** (Накладная CustomMembers)

        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Вес CustomAttributes)

        // *** End programmer edit section *** (Накладная.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Вес Get start)

                // *** End programmer edit section *** (Накладная.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (Накладная.Вес Get end)

                // *** End programmer edit section *** (Накладная.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Вес Set start)

                // *** End programmer edit section *** (Накладная.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (Накладная.Вес Set end)

                // *** End programmer edit section *** (Накладная.Вес Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ДатаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Накладная.ДатаОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ДатаОтгрузки Get start)

                // *** End programmer edit section *** (Накладная.ДатаОтгрузки Get start)
                System.DateTime result = this.fДатаОтгрузки;
                // *** Start programmer edit section *** (Накладная.ДатаОтгрузки Get end)

                // *** End programmer edit section *** (Накладная.ДатаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ДатаОтгрузки Set start)

                // *** End programmer edit section *** (Накладная.ДатаОтгрузки Set start)
                this.fДатаОтгрузки = value;
                // *** Start programmer edit section *** (Накладная.ДатаОтгрузки Set end)

                // *** End programmer edit section *** (Накладная.ДатаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Примечание CustomAttributes)

        // *** End programmer edit section *** (Накладная.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Примечание Get start)

                // *** End programmer edit section *** (Накладная.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (Накладная.Примечание Get end)

                // *** End programmer edit section *** (Накладная.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Примечание Set start)

                // *** End programmer edit section *** (Накладная.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (Накладная.Примечание Set end)

                // *** End programmer edit section *** (Накладная.Примечание Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Статус CustomAttributes)

        // *** End programmer edit section *** (Накладная.Статус CustomAttributes)
        public virtual IIS.SkaldKurs.СостояниеНакладной Статус
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Статус Get start)

                // *** End programmer edit section *** (Накладная.Статус Get start)
                IIS.SkaldKurs.СостояниеНакладной result = this.fСтатус;
                // *** Start programmer edit section *** (Накладная.Статус Get end)

                // *** End programmer edit section *** (Накладная.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Статус Set start)

                // *** End programmer edit section *** (Накладная.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Накладная.Статус Set end)

                // *** End programmer edit section *** (Накладная.Статус Set end)
            }
        }
        
        /// <summary>
        /// ФИОПолучателя.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ФИОПолучателя CustomAttributes)

        // *** End programmer edit section *** (Накладная.ФИОПолучателя CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОПолучателя
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Get start)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Get start)
                string result = this.fФИОПолучателя;
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Get end)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Set start)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Set start)
                this.fФИОПолучателя = value;
                // *** Start programmer edit section *** (Накладная.ФИОПолучателя Set end)

                // *** End programmer edit section *** (Накладная.ФИОПолучателя Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Заказ CustomAttributes)

        // *** End programmer edit section *** (Накладная.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.SkaldKurs.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Заказ Get start)

                // *** End programmer edit section *** (Накладная.Заказ Get start)
                IIS.SkaldKurs.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Накладная.Заказ Get end)

                // *** End programmer edit section *** (Накладная.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Заказ Set start)

                // *** End programmer edit section *** (Накладная.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Накладная.Заказ Set end)

                // *** End programmer edit section *** (Накладная.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Накладная.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.SkaldKurs.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Сотрудник Get start)

                // *** End programmer edit section *** (Накладная.Сотрудник Get start)
                IIS.SkaldKurs.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Накладная.Сотрудник Get end)

                // *** End programmer edit section *** (Накладная.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Сотрудник Set start)

                // *** End programmer edit section *** (Накладная.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Накладная.Сотрудник Set end)

                // *** End programmer edit section *** (Накладная.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной CustomAttributes)

        // *** End programmer edit section *** (Накладная.ЗаписьВНакладной CustomAttributes)
        public virtual IIS.SkaldKurs.DetailArrayOfЗаписьВНакладной ЗаписьВНакладной
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Get start)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Get start)
                if ((this.fЗаписьВНакладной == null))
                {
                    this.fЗаписьВНакладной = new IIS.SkaldKurs.DetailArrayOfЗаписьВНакладной(this);
                }
                IIS.SkaldKurs.DetailArrayOfЗаписьВНакладной result = this.fЗаписьВНакладной;
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Get end)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Set start)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Set start)
                this.fЗаписьВНакладной = value;
                // *** Start programmer edit section *** (Накладная.ЗаписьВНакладной Set end)

                // *** End programmer edit section *** (Накладная.ЗаписьВНакладной Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НакладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяE", typeof(IIS.SkaldKurs.Накладная));
                }
            }
            
            /// <summary>
            /// "НакладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяL", typeof(IIS.SkaldKurs.Накладная));
                }
            }
        }
    }
}
